### ISSUE TITLE
--dev flag generates "No such file" error

### ISSUE THREAD

**Issue by acrellin** [fritz-marshal/fritz#202]
```
./fritz run --init --dev                                    
Checking system dependencies:                                                                             
[✓] python >= 3.7                 [   3.8.8]                                                              
[✓] docker >= 18.06               [19.03.13]                                                              
[✓] docker-compose >= 1.22.0      [  1.25.0]                                                              
--------------------                                                                                      
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'          
Traceback (most recent call last):                                                                        
  File "./fritz", line 893, in <module>                                                                   
    getattr(sys.modules[__name__], args.command)(args)                                                    
  File "./fritz", line 403, in run                                                                        
    build(args=args)                                                                                      
  File "./fritz", line 265, in build                                                                      
    subprocess.run(c, cwd="kowalski", check=True)                                                         
  File "/home/arien/anaconda3/envs/fritz/lib/python3.8/subprocess.py", line 516, in run                   
    raise CalledProcessError(retcode, process.args,                                                       
subprocess.CalledProcessError: Command '['pip', 'install', '-r', 'requirements.txt']' returned non-zero exit status 1.                                                                                              
```

**Comment by dmitryduev** [comment]
This flag was removed altogether, so closing.
