### ISSUE TITLE
Thumbnail handler falls over on PGIR alerts

### ISSUE THREAD

**Issue by mcoughlin** [fritz-marshal/fritz#485]
[19:11:35 models.thumbnail] Error deleting thumbnail file /skyportal/static/thumbnails/PGIR19agmdyq_ref.png: [Errno 2] No such file or directory: '/skyportal/static/thumbnails/PGIR19agmdyq_ref.png'
2022-10-30 19:11:35,534 - tornado.application - ERROR - Uncaught exception PATCH /api/thumbnailPath?pageNumber=2 (136.152.143.213)
HTTPServerRequest(protocol='http', host='fritz.science', method='PATCH', uri='/api/thumbnailPath?pageNumber=2', version='HTTP/1.0', remote_ip='136.152.143.213')
Traceback (most recent call last):
  File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/skyportal/baselayer/app/access.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/skyportal/baselayer/app/access.py", line 75, in wrapper
    return method(self, *args, **kwargs)
  File "/skyportal/skyportal/handlers/api/thumbnail.py", line 481, in patch
    ok = check_thumbnail_file(
  File "/skyportal/skyportal/handlers/api/thumbnail.py", line 670, in check_thumbnail_file
    post_alert(
  File "/skyportal/skyportal/handlers/api/alert.py", line 212, in post_alert
    raise ValueError(f"{object_id} not found on Kowalski")
ValueError: PGIR19agmdyq not found on Kowalski

**Comment by mcoughlin** [comment]
Closing as obsolete: PGIR is not ingested in the current Fritz/BOOM pipeline.
