### ISSUE TITLE
"fritz --init" failure

### ISSUE THREAD

**Issue by caseyjlaw** [fritz-marshal/fritz#545]
**Describe the bug**

I'm following instructions to run my own instance from docs.fritz.science. It uses docker and docker compose and seems to get most of the way though. However, it fails in setting up skyportal and/or a database.

**To Reproduce**

Following instructions on github: https://docs.fritz.science/run_your_own.html. I cloned the latest on github and set up a virtual environment. Then ran `./fritz run --init`.

**Log**

```
(fritz-env) realfast-vml$ ./fritz run --init
[✓] Initializing submodules
Checking system dependencies:
[✓] python >= 3.7
[✓] docker >= 18.06
[✓] docker-compose >= 1.22.0

Checking python requirements:
[✓] penquins>=2.3.2
[✓] pre-commit
[✓] deepdiff>=5.0.2
[✓] pyyaml>=5.3.1
[✓] pyjwt>=2.0.1
[✓] gsutil>=4.56
[✓] fire>=0.3.1
[✓] pymongo>=4.4.0
[✓] sphinx<3
[✓] sphinx_press_theme
[✓] requests>=2.26
[✓] jinja2<3.1.0
[✓] myst-parser
[✓] questionary>=1.8.1
--------------------
Requirement already satisfied: deepdiff>=5.0.2 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (7.0.1)
Requirement already satisfied: fire>=0.3.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: pyyaml>=5.3.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (6.0.1)
Requirement already satisfied: gsutil>=4.56 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (5.27)
Requirement already satisfied: questionary>=1.8.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (2.0.1)
Requirement already satisfied: ordered-set<4.2.0,>=4.1.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from deepdiff>=5.0.2->-r requirements.txt (line 1)) (4.1.0)
Requirement already satisfied: six in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from fire>=0.3.1->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: termcolor in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from fire>=0.3.1->-r requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: argcomplete>=1.9.4 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (3.3.0)
Requirement already satisfied: crcmod>=1.7 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (1.7)
Requirement already satisfied: fasteners>=0.14.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (0.19)
Requirement already satisfied: gcs-oauth2-boto-plugin>=3.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (3.0)
Requirement already satisfied: google-apitools>=0.5.32 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (0.5.32)
Requirement already satisfied: httplib2==0.20.4 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (0.20.4)
Requirement already satisfied: google-reauth>=0.1.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (0.1.1)
Requirement already satisfied: monotonic>=1.4 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (1.6)
Requirement already satisfied: pyOpenSSL>=0.13 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (24.1.0)
Requirement already satisfied: retry-decorator>=1.0.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gsutil>=4.56->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: google-auth>=2.5.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (2.29.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from httplib2==0.20.4->gsutil>=4.56->-r requirements.txt (line 4)) (3.1.2)
Requirement already satisfied: prompt_toolkit<=3.0.36,>=2.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from questionary>=1.8.1->-r requirements.txt (line 5)) (3.0.36)
Requirement already satisfied: rsa==4.7.2 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gcs-oauth2-boto-plugin>=3.0->gsutil>=4.56->-r requirements.txt (line 4)) (4.7.2)
Requirement already satisfied: boto>=2.29.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gcs-oauth2-boto-plugin>=3.0->gsutil>=4.56->-r requirements.txt (line 4)) (2.49.0)
Requirement already satisfied: oauth2client>=2.2.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from gcs-oauth2-boto-plugin>=3.0->gsutil>=4.56->-r requirements.txt (line 4)) (4.1.3)
Requirement already satisfied: pyasn1>=0.1.3 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from rsa==4.7.2->gcs-oauth2-boto-plugin>=3.0->gsutil>=4.56->-r requirements.txt (line 4)) (0.6.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from google-auth>=2.5.0->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from google-auth>=2.5.0->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (0.4.0)
Requirement already satisfied: aiohttp<4.0.0.dev0,>=3.6.2 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (3.9.5)
Requirement already satisfied: requests<3.0.0.dev0,>=2.20.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: pyu2f in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from google-reauth>=0.1.0->gsutil>=4.56->-r requirements.txt (line 4)) (0.1.5)
Requirement already satisfied: wcwidth in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from prompt_toolkit<=3.0.36,>=2.0->questionary>=1.8.1->-r requirements.txt (line 5)) (0.2.13)
Requirement already satisfied: cryptography<43,>=41.0.5 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from pyOpenSSL>=0.13->gsutil>=4.56->-r requirements.txt (line 4)) (42.0.5)
Requirement already satisfied: aiosignal>=1.1.2 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from aiohttp<4.0.0.dev0,>=3.6.2->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from aiohttp<4.0.0.dev0,>=3.6.2->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (21.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from aiohttp<4.0.0.dev0,>=3.6.2->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from aiohttp<4.0.0.dev0,>=3.6.2->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from aiohttp<4.0.0.dev0,>=3.6.2->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from aiohttp<4.0.0.dev0,>=3.6.2->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (4.0.3)
Requirement already satisfied: cffi>=1.12 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from cryptography<43,>=41.0.5->pyOpenSSL>=0.13->gsutil>=4.56->-r requirements.txt (line 4)) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.20.0->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.20.0->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.20.0->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.20.0->google-auth[aiohttp]>=2.5.0->gsutil>=4.56->-r requirements.txt (line 4)) (2024.2.2)
Requirement already satisfied: pycparser in /users/claw/code/fritz/fritz-env/lib/python3.8/site-packages (from cffi>=1.12->cryptography<43,>=41.0.5->pyOpenSSL>=0.13->gsutil>=4.56->-r requirements.txt (line 4)) (2.22)
Applying fritz-specific patches to SkyPortal
Building SkyPortal docker image (tag: skyportal/web:latest)
[+] Building 876.1s (14/14) FINISHED                                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                                           0.1s
 => => transferring dockerfile: 2.77kB                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                0.9s
 => [internal] load .dockerignore                                                                                                              0.0s
 => => transferring context: 331B                                                                                                              0.0s
 => [1/9] FROM docker.io/library/ubuntu:22.04@sha256:1b8d8ff4777f36f19bfe73ee4df61e3a0b789caeff29caa019539ec7c9a57f95                          0.0s
 => [internal] load build context                                                                                                              0.6s
 => => transferring context: 249.84kB                                                                                                          0.5s
 => CACHED [2/9] RUN apt-get update &&     apt-get install -y curl build-essential software-properties-common ca-certificates gnupg &&     mk  0.0s
 => CACHED [3/9] RUN add-apt-repository ppa:ondrej/nginx-mainline -y &&  apt update -y &&  apt install -y nginx libnginx-mod-http-brotli-stat  0.0s
 => CACHED [4/9] RUN apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     useradd --create-home --shell /bin/bash skypor  0.0s
 => CACHED [5/9] RUN python3 -m venv /skyportal_env &&         bash -c "source /skyportal_env/bin/activate &&     pip install --upgrade pip==  0.0s
 => CACHED [6/9] RUN git clone https://github.com/Theodlz/snid-install-ubuntu.git &&     cd snid-install-ubuntu && chmod +x install.sh && bas  0.0s
 => [7/9] ADD . /skyportal                                                                                                                     2.9s
 => [8/9] WORKDIR /skyportal                                                                                                                   0.0s
 => [9/9] RUN bash -c "    cp docker.yaml config.yaml &&         source /skyportal_env/bin/activate &&     export NPM_CONFIG_LEGACY_PEER_DE  830.9s
 => exporting to image                                                                                                                        40.6s 
 => => exporting layers                                                                                                                       40.5s 
 => => writing image sha256:90961a923585a7874475d1eaa9188ead4983203720f99eda463384bb11cc33ae                                                   0.0s 
 => => naming to docker.io/skyportal/web:latest                                                                                                0.0s 
Creating skyportal_db_1 ... done
Creating skyportal_web_1 ... done

Welcome to SkyPortal v0.9.dev0+git20240414.5e77d884+fritz.70d62e0 (https://skyportal.io)

Requirement already satisfied: packaging in /skyportal_env/lib/python3.10/site-packages (23.2)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Checking system dependencies:
[✓] nginx >= 1.7                  [  1.25.5]
[✓] psql >= 12.0                  [   14.11]
[✓] npm >= 8.3.2                  [  10.5.0]
[✓] node >= 16.14.0               [ 20.12.2]
[✓] python >= 3.8                 [ 3.10.12]

[✓] Baselayer installed inside of app
--------------------
/skyportal/baselayer/tools/pip_install_requirements.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
[✓] Verifying Python package dependencies
[✓] Silently executing: baselayer/tools/check_js_deps.sh
[✗] Silently executing: baselayer/tools/db_init.py -f --config=config.yaml

! Failure (exit code 1).
--- stderr ---
Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml
[21:05:44 db_init] Initializing databases
[✓] Creating user [skyportal]
[✗] Removing database [skyportal]
Could not delete database: 

  psql: error: connection to server at "db" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
--- end ---
make[1]: *** [baselayer/Makefile:56: db_clear] Error 1
make: *** [Makefile:74: db_clear] Error 2

Welcome to SkyPortal v0.9.dev0+git20240414.5e77d884+fritz.70d62e0 (https://skyportal.io)

Requirement already satisfied: packaging in /skyportal_env/lib/python3.10/site-packages (23.2)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Checking system dependencies:
[✓] nginx >= 1.7                  [  1.25.5]
[✓] psql >= 12.0                  [   14.11]
[✓] npm >= 8.3.2                  [  10.5.0]
[✓] node >= 16.14.0               [ 20.12.2]
[✓] python >= 3.8                 [ 3.10.12]

[✓] Baselayer installed inside of app
--------------------
/skyportal/baselayer/tools/pip_install_requirements.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
[✓] Verifying Python package dependencies
[✓] Silently executing: baselayer/tools/check_js_deps.sh

Initializing database:
  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml
[21:06:31 db_init] Initializing databases
[✓] Creating user [skyportal]
[✓] Creating database [skyportal]
[·] Creating database [skyportal_test]
Warning: could not create db skyportal_test



  You should create it manually by invoking `createdb`.
  Then, execute:

    PGPASSWORD="password" psql -U skyportal --no-password -h db -p 5432 -c "GRANT ALL PRIVILEGES ON DATABASE skyportal_test TO skyportal;" skyportal_test

[✓] Creating database [skyportal_test]
[✓] Testing database connection to [skyportal]


Welcome to SkyPortal v0.9.dev0+git20240414.5e77d884+fritz.70d62e0 (https://skyportal.io)


Welcome to SkyPortal v0.9.dev0+git20240414.5e77d884+fritz.70d62e0 (https://skyportal.io)

Requirement already satisfied: packaging in /skyportal_env/lib/python3.10/site-packages (23.2)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Checking system dependencies:
[✓] nginx >= 1.7                  [  1.25.5]
[✓] psql >= 12.0                  [   14.11]
[✓] npm >= 8.3.2                  [  10.5.0]
[✓] node >= 16.14.0               [ 20.12.2]
[✓] python >= 3.8                 [ 3.10.12]

[✓] Baselayer installed inside of app
--------------------
/skyportal/baselayer/tools/pip_install_requirements.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
[✓] Verifying Python package dependencies
[✓] Silently executing: baselayer/tools/check_js_deps.sh
/skyportal/tools/data_loader.py:12: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml
Testing connection...No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
No token specified; reading from SkyPortal generated .tokens.yaml
Loaded token from SkyPortal provisioned .tokens.yaml
Expected HTTP 200, received 503. Trying again.
Expected HTTP 200, received 503. Trying again.
Expected HTTP 200, received 503. Trying again.
Expected HTTP 200, received 503. Trying again.
Expected HTTP 200, received 503. Trying again.
Expected HTTP 200, received 503. Trying again.
FAIL
Fatal: could not connect to server (HTTP status 503)
make: *** [Makefile:64: load_seed_data] Error 255
Failed to load seed data into SkyPortal, waiting to retry...

Welcome to SkyPortal v0.9.dev0+git20240414.5e77d884+fritz.70d62e0 (https://skyportal.io)

Requirement already satisfied: packaging in /skyportal_env/lib/python3.10/site-packages (23.2)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Checking system dependencies:
[✓] nginx >= 1.7                  [  1.25.5]
[✓] psql >= 12.0                  [   14.11]
[✓] npm >= 8.3.2                  [  10.5.0]
[✓] node >= 16.14.0               [ 20.12.2]
[✓] python >= 3.8                 [ 3.10.12]

[✓] Baselayer installed inside of app
--------------------
/skyportal/baselayer/tools/pip_install_requirements.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
[✓] Verifying Python package dependencies
[✓] Silently executing: baselayer/tools/check_js_deps.sh
[✗] Silently executing: baselayer/tools/db_init.py -f --config=config.yaml

! Failure (exit code 1).
--- stderr ---
Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml
[21:12:22 db_init] Initializing databases
[✓] Creating user [skyportal]
[✗] Removing database [skyportal]
Could not delete database: 

  psql: error: connection to server at "db" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
--- end ---
make[1]: *** [baselayer/Makefile:56: db_clear] Error 1
make: *** [Makefile:74: db_clear] Error 2

Welcome to SkyPortal v0.9.dev0+git20240414.5e77d884+fritz.70d62e0 (https://skyportal.io)



...
[retries installation a few times, but database already exists]
...
[eventually]
...



Failed to load seed data into SkyPortal, waiting to retry...
Traceback (most recent call last):
  File "/opt/local/stow/python-3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/local/stow/python-3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/users/claw/code/fritz/launcher/__main__.py", line 72, in <module>
    fire.Fire(
  File "/users/claw/code/fritz/fritz-env/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/users/claw/code/fritz/fritz-env/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/users/claw/code/fritz/fritz-env/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/users/claw/code/fritz/launcher/commands/run.py", line 20, in run
    build(
  File "/users/claw/code/fritz/launcher/commands/build.py", line 134, in build
    raise RuntimeError("Failed to init SkyPortal and load seed data")

```

**Platform information:**

- Redhat 7.9
- Docker 26.0.1
- docker-compose 1.28.6

**Comment by mcoughlin** [comment]
Closing as stale: several years old and no longer applicable to the current Fritz/BOOM architecture. Please refile if still relevant.
